language: swift

osx_image: xcode12.5
env:
  matrix:
    - TEST_SDK=iphonesimulator14.5 OS=12.5 NAME='iPhone XR'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project BluetoothWrapper.xcodeproj -scheme BluetoothWrapper -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
